### ISSUE TITLE
supported extend rather than overwrite for list-typed config options

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#132]
cfr. https://github.com/hpcugent/easybuild-framework/issues/985

When values for the `--robot` option are passed via the different 'levels' (config file, environment, cmdline), currently the command line wins: any list of paths specified in a config file are being overwritten when `--robot` is used without specifying an argument.

It would be nicer if that didn't happen, and if paths specified on the cmdline were prepended (while preserving order) to other paths specified via environment or config file.

So, with `robot = /cfg1,/cfg2` in the config file, `$EASYBUILD_ROBOT=/env1,/env2` and `--robot=/cmdline1:/cmdline2`, the resulting robot path should be `/cmdline1:/cmdline2:/env1:/env2:/cfg1:/cfg2`

**Comment by stdweird** [comment]
@boegel i'd rather not support this. commandline precedes environment preceds configfile is a very simple principle i'd rather not divert from.

**Comment by boegel** [comment]
alternative implemented via #162
