### ISSUE TITLE
options with 'store' action consume other options as values

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#184]
see https://github.com/hpcugent/easybuild/issues/113

**Comment by stdweird** [comment]
so the issue is that the option parser should reject values that are valid options? and throw what error in this case? (and how would you like to pass the value `-D` to the option `-b`?)

**Comment by boegel** [comment]
If `-D` is not considered a valid value for `-b`, then the error `'missing argument'` needs to be thrown, since `-b` requires an argument (since it's a `store` action).

I'm not sure if it's possible to discriminate, but I guess `-b=-D` would be acceptable, since that's not ambiguous.

**Comment by stdweird** [comment]
makes sense. the error could make this clearer like `missing argument: trying to pass valid option -D is not allowed (use -b=-D instead)`, but i don't know if i can distinguish between `-b -D` and `-b=-D`.

**Comment by boegel** [comment]
I'm sure you meant to say "I'm not sure how yet to distuingish between `-b -D` and `-b=-D`, but I can figure out a dirty hack" ;-)

**Comment by stdweird** [comment]
reading the code, the shortoptions seem to have `-bVALUE` instead of `-b=VALUE`. only the longopts have `--longopt=VALUE`. raising the error should be trivial however.

**Comment by boegel** [comment]
Well, if we can mention "use `--only-blocks=-D` instead" when someone is trying to use `-b -D`, I'm all for it.

**Comment by stdweird** [comment]
hmm, it's a tiny bit more complicated then i tought, since this is only an issue on the commandline.

**Comment by stdweird** [comment]
if using the longopt only (even when the commandline was shortopt) to force the option-as-value is acceptable, that might make things a bit simpler.

**Comment by boegel** [comment]
You mean, only support `--only-blocks=-D` (but not the equivalent of `-b=-D`)? Sure, works for me.

**Comment by ehiggs** [comment]
How does this work for store_int given `-D -7`

**Comment by boegel** [comment]
@ehiggs: nice one :-)
I guess we'll need to make (another) exception for `store_int` (or maybe none at all, and just let it complain that `-x` is not a valid integer)?

**Comment by stdweird** [comment]
how is `-7` a valid option?

**Comment by boegel** [comment]
Well, it can be both a valid option (if you're crazy enough to use `-7` as a short option for `--seven`), and a valid value (for a `store_int` option), I guess.

**Comment by stdweird** [comment]
well, you'll have to set `-x-7` or `--longx=-7` then

**Comment by ehiggs** [comment]
-4, -6: 

```
$ ip
Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }
       ip [ -force ] -batch filename
where  OBJECT := { link | addr | addrlabel | route | rule | neigh | ntable |
                   tunnel | tuntap | maddr | mroute | mrule | monitor | xfrm |
                   netns | l2tp | tcp_metrics | token | netconf }
       OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
                    -f[amily] { inet | inet6 | ipx | dnet | bridge | link } |
                    -4 | -6 | -I | -D | -B | -0 |
                    -l[oops] { maximum-addr-flush-attempts } |
                    -o[neline] | -t[imestamp] | -b[atch] [filename] |
                    -rc[vbuf] [size]}
```

**Comment by boegel** [comment]
works for me, bet passing negative integers as a value is going to be rare enough; we don't need to do anything special to support something like `-7` as an option afaik
