### ISSUE TITLE
Add `python setup.py test` lib shim custom command.

### ISSUE THREAD

**Issue by itkovian** [hpcugent/vsc-base#192]
See https://github.ugent.be/hpcugent/clusterbuildrpm-server/pull/18

**Comment by stdweird** [comment]
the trickery should be extended to only run certain tests via a filter set in enviroment, eg.
```bash
PTEST='x' python setup.py test
```
should only run tests which match `PTEST` (inlcuding the test methods and modules)
afaik, there's no clean way to do that now.

**Comment by boegel** [comment]
I'm not very comfortable with the term 'trickery' in all of this...

If we need to hack in nasty stuff to make things work, we're probably doing something wrong?
